version: '3.9'

services:
  db:
    image: postgres:15
    container_name: laprovence_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: laprovence
    ports:
      - "5445:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: